kind: pipeline
name: lint

steps:
- name: lint
  image: golang:1.11
  commands:
  - golint -set_exit_status cmd pkg

---
kind: pipeline
name: build

workspace:
  base: /go
  path: src/github.com/laszlocph/tsdbinfo

steps:
- name: prereqs
  image: golang:1.11
  commands:
    - mkdir /go/bin
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

- name: build
  image: golang:1.11
  commands:
    - dep ensure
    - env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
    - mv tsdbinfo tsdbinfo-linux-amd64
    - env GOOS=darwin GOARCH=amd64 go build
    - mv tsdbinfo tsdbinfo-mac-amd64

- name: release
  image: golang:1.11
  when:
    event:
    - tag
  commands:
    - mv tsdbinfo-linux-amd64 tsdbinfo-$DRONE_TAG-linux-amd64
    - mv tsdbinfo-mac-amd64 tsdbinfo-$DRONE_TAG-mac-amd64
    - ./misc/upload-github-release-asset.sh github_api_token=$github_api_token owner=laszlocph repo=tsdbinfo tag=$DRONE_TAG filename=./tsdbinfo-$DRONE_TAG-linux-amd64
    - ./misc/upload-github-release-asset.sh github_api_token=$github_api_token owner=laszlocph repo=tsdbinfo tag=$DRONE_TAG filename=./tsdbinfo-$DRONE_TAG-mac-amd64
  environment:
    github_api_token:
      from_secret: github_api_token

